/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/kimsman/project/2025/ajou-pwd-2025/lumo-stage/client/public/wooden_mannequine/scene.gltf -o /Users/kimsman/project/2025/ajou-pwd-2025/lumo-stage/client/src/components/Mannequin.jsx 
Author: madeofmesh (https://sketchfab.com/madeofmesh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-mannequin-lay-figure-rigged-f119f296833e4d4d9a8fc24dfc0533d6
Title: Wooden Mannequin (Lay Figure) - Rigged
*/

import React, { useEffect, useMemo, useRef, forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useGraph } from '@react-three/fiber';
import { SkeletonUtils } from 'three-stdlib';
import useStore from '../store';

export const Mannequin = forwardRef(({ id, pose, ...props }, ref) => {
  const { scene, materials } = useGLTF('/wooden_mannequine/scene.gltf');
  // Create a unique clone for each instance to allow independent animations
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);

  const { initializePose, selectMannequin, setHighlightedBone } = useStore();
  const hasInitialized = useRef(false);

  const skinnedMesh = nodes.Object_9; // Find the skinned mesh from the cloned graph

  useEffect(() => {
    // Initialize pose from the model's default, but do it only once per instance
    if (skinnedMesh && !hasInitialized.current) {
      const initialPose = {};
      Object.keys(pose).forEach(boneName => {
        const bone = nodes[boneName];
        if (bone) {
          initialPose[boneName] = { x: bone.rotation.x, y: bone.rotation.y, z: bone.rotation.z };
        }
      });
      initializePose(id, initialPose);
      hasInitialized.current = true;
    }
  }, [skinnedMesh, id, pose, initializePose, nodes]);

  useFrame(() => {
    // Apply pose from props to the unique cloned bones
    if (!skinnedMesh || !hasInitialized.current) return;
    Object.keys(pose).forEach(boneName => {
      const bone = nodes[boneName];
      if (bone) {
        const { x, y, z } = pose[boneName];
        bone.rotation.set(x, y, z);
      }
    });
  });

  const handleJointClick = (event) => {
    event.stopPropagation();
    selectMannequin(id);
    if (!skinnedMesh) return;

    const geometry = skinnedMesh.geometry;
    const skeleton = skinnedMesh.skeleton;
    const bones = skeleton.bones;
    const boneNames = Object.keys(pose);

    if (event.face) {
      const vertexIndex = event.face.a;
      const skinIndex = geometry.attributes.skinIndex.getX(vertexIndex);
      const bone = bones[skinIndex];
      if (bone && boneNames.includes(bone.name)) {
        setHighlightedBone(bone.name);
      }
    }
  };

  return (
    <group ref={ref} {...props} dispose={null}>
       <group rotation={[-Math.PI / 2, 0, 0]} scale={2.329}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 97.263, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              castShadow
              receiveShadow
              geometry={skinnedMesh.geometry}
              material={materials.lay_figure_material}
              skeleton={skinnedMesh.skeleton}
              onClick={handleJointClick}
            />
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload('/wooden_mannequine/scene.gltf');
